### ISSUE TITLE
Request on sharing dataset

### ISSUE THREAD

**Issue by supinfl** [mt-cly/FPR#2]
Hi,

Thank you for sharing your work. I have a question regarding the dataset used in the paper. The provided link leads to the original dataset with only 2,000+ segmentation annotations. However, the paper mentions an augmented dataset with 10,582 images.

Could you please provide a link to the augmented dataset or instructions on how to obtain it?

Thank you in advance!

**Comment by mt-cly** [comment]
Hi, 
In WSSS, it is usually to take SBD dataset as the augmentation for VOC 2012. You can obtain the SBD part from the official website or links from repos like https://github.com/xulianuwa/MCTformer .

**Comment by supinfl** [comment]
Thank you very much!
