### ISSUE TITLE
Confusion on matching fpr.log with paper result

### ISSUE THREAD

**Issue by supinfl** [mt-cly/FPR#3]
Hi,

Thank you for providing the code and logs related to the FPR paper. I have been going through the logs, but I'm having trouble matching the precision, recall, and mIoU values reported in the paper with the outputs from the eval_cam function.

It seems like eval_cam was run with multiple thresholds, and each threshold outputs different precision, recall, and mIoU values. Could you please clarify which threshold corresponds to the results reported in the paper?

Thank you for your help!

**Comment by mt-cly** [comment]
Hi,
Yes, you can draw a mIoU curve across different thresholds to find peak performance. I set the threshold to 0.06 since it achieves best performance with 54.7% mIoU (please refer to log file), which is closed to paper-reported 54.3%.

**Comment by supinfl** [comment]
Thank you so much for your prompt and detailed response regarding the threshold that achieves the best mIoU.

If I may ask for a bit more clarification: Are the precision and recall values reported in the paper taken from the same threshold that provides the best mIoU (in this case, 0.06)? Or were the precision and recall values selected independently from different thresholds to reflect their respective best values?

I sincerely appreciate your time and help with this!

**Comment by mt-cly** [comment]
mIoU, Precision, and Recall, all of them are selected with same threshold, i.e., 0.06. The slight difference between paper reported  and log file is caused by some factors like initial seed and different devices.

**Comment by supinfl** [comment]
Thank you very much!
